# Generated by Django 4.1.7 on 2023-04-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univ_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teaches',
            options={'managed': True},
        ),
    ]
