# Generated by Django 4.1.7 on 2023-04-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ_database', '0005_alter_teaches_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('doi', models.CharField(db_column='DOI', max_length=100, primary_key=True, serialize=False)),
                ('paper_title', models.CharField(blank=True, db_column='Paper_Title', max_length=100, null=True)),
                ('publish_date', models.DateField(blank=True, db_column='Publish_date', null=True)),
                ('budget', models.IntegerField(blank=True, db_column='Budget', null=True)),
            ],
            options={
                'db_table': 'papers',
                'managed': False,
            },
        ),
    ]
