# Generated by Django 4.1.7 on 2023-04-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(db_column='Course_ID', max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=50, null=True)),
                ('credits', models.IntegerField(blank=True, db_column='Credits', null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=25, primary_key=True, serialize=False)),
                ('building', models.CharField(blank=True, db_column='Building', max_length=10, null=True)),
                ('budget', models.IntegerField(blank=True, db_column='Budget', null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=20, null=True)),
                ('salary', models.IntegerField(blank=True, db_column='Salary', null=True)),
            ],
            options={
                'db_table': 'instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prereq_id', models.CharField(blank=True, db_column='Prereq_ID', max_length=6, null=True)),
            ],
            options={
                'db_table': 'pre_req',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_id', models.IntegerField(db_column='Sec_ID')),
                ('semester', models.IntegerField(db_column='Semester')),
                ('year', models.IntegerField(db_column='Year')),
                ('building', models.CharField(blank=True, db_column='Building', max_length=6, null=True)),
                ('room', models.CharField(blank=True, db_column='Room', max_length=3, null=True)),
                ('capacity', models.IntegerField(blank=True, db_column='Capacity', null=True)),
            ],
            options={
                'db_table': 'section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=40, null=True)),
                ('tot_cred', models.IntegerField(blank=True, db_column='Tot_Cred', null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, db_column='Grade', max_length=2, null=True)),
            ],
            options={
                'db_table': 'takes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'teaches',
                'managed': False,
            },
        ),
    ]
