# Generated by Django 4.1.7 on 2023-04-19 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univ_database', '0002_alter_teaches_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaches',
            name='course',
            field=models.ForeignKey(db_column='Course_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teaches_courseID', to='univ_database.section'),
        ),
        migrations.AddField(
            model_name='teaches',
            name='sec',
            field=models.ForeignKey(db_column='Sec_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teaches_sectionID', to='univ_database.section'),
        ),
        migrations.AddField(
            model_name='teaches',
            name='semester',
            field=models.ForeignKey(db_column='Semester', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teaches_semesster', to='univ_database.section'),
        ),
        migrations.AddField(
            model_name='teaches',
            name='teacher',
            field=models.ForeignKey(db_column='Teacher_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teaches_teacher', to='univ_database.instructor'),
        ),
        migrations.AddField(
            model_name='teaches',
            name='year',
            field=models.ForeignKey(db_column='Year', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teaches_year', to='univ_database.section'),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='teaches',
            unique_together={('course', 'sec', 'semester', 'year')},
        ),
    ]
