# Generated by Django 4.1.7 on 2023-04-19 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univ_database', '0003_teaches_course_teaches_sec_teaches_semester_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaches',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='course',
            field=models.ForeignKey(db_column='Course_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='teaches_courseID', to='univ_database.section'),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='sec',
            field=models.ForeignKey(db_column='Sec_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='teaches_sectionID', to='univ_database.section'),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='semester',
            field=models.ForeignKey(db_column='Semester', on_delete=django.db.models.deletion.DO_NOTHING, related_name='teaches_semester', to='univ_database.section'),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='teacher',
            field=models.ForeignKey(db_column='Teacher_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='teaches_teacher', to='univ_database.instructor'),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='year',
            field=models.ForeignKey(db_column='Year', on_delete=django.db.models.deletion.DO_NOTHING, related_name='teaches_year', to='univ_database.section'),
        ),
        migrations.AlterUniqueTogether(
            name='teaches',
            unique_together={('course', 'sec', 'semester', 'year', 'teacher')},
        ),
    ]
