# Generated by Django 4.1.7 on 2023-04-19 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univ_database', '0004_alter_teaches_unique_together_alter_teaches_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teaches',
            options={'managed': False},
        ),
    ]
